/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Reader */

#ifndef _Included_Reader
#define _Included_Reader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Reader
 * Method:    read
 * Signature: ([BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Reader_read
  (JNIEnv *, jobject, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
