/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Smooth1dDriver */

#ifndef _Included_Smooth1dDriver
#define _Included_Smooth1dDriver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
