/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrUtils */

#ifndef _Included_ArrUtils
#define _Included_ArrUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrUtils
 * Method:    extrema
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_ArrUtils_extrema
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
