/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Utils */

#ifndef _Included_Utils
#define _Included_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Utils
 * Method:    max
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Utils_max
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Utils
 * Method:    maxarr
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_Utils_maxarr
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
